>D
;*****
;
;*****
; After selecting a script, be sure to activate it and reboot!
; Nachdem auswaehlen eines Scripts, unbedingt dieses aktivieren und einen Neustart durchfuehren!
;*****
>B
=>sensor53 r
; Set teleperiod to 10sec
; Interval fuer das Senden von Daten auf 10 Sekunden setzen
tper=10
>M 1
;
; Setupline
+1,3,o,0,300,Strom,1,30,2F3F210D0A,063030300D0A
1,1.8.0*00(@1,Gesamtverbrauch,kWh,Pges,2
#