>D
;*****
;
;*****
; - Haken bei "Skript aktivieren" setzen
; - Skript auswaehlen
; - Speichern anklicken
;*****
>B
=>sensor53 r
;
>M 1
;
; Setupline
+1,3,s,16,9600,DWSB122
1,77070100010800ff@1000,Energie bezogen,kWh,energy,0
1,77070100020800ff@1000,Energie geliefert,kWh,energy,0
1,7707010060320101@#,Service ID,,meter_id,0
1,77010b0a01445a47@#,Unbekannt,,unknown,0
1,77070100600100ff@#,Zählernummer,,meter_number,0
#
