>D
;*****
;
;*****
; After selecting a script, be sure to activate it and reboot!
; Nachdem auswaehlen eines Scripts, unbedingt dieses aktivieren und einen Neustart durchfuehren!
;*****
>B
=>sensor53 r
; Set teleperiod to 10sec
; Interval fuer das Senden von Daten auf 10 Sekunden setzen
tper=10
>M 1
;
; Setupline
+1,3,s,16,9600,DWS7412
1,77070100010800ff@1000,Energy,kWh,energy,4
1,77070100240700ff@1,Power,W,power,2
1,7707010060320101@#,Service ID,,meter_id,0
#