>D
;*****
; DZG-DxS7410.2V.G2
;
; DZG-DVS74 4L-Drehstromzähler
; DZG-DWS74 4L-Zähler mit Option Einphasenzähler
;*****
; - Haken bei "Skript aktivieren" setzen
; - Skript auswaehlen
; - Speichern anklicken
;*****
>B
=>sensor53 r
;
>M 1
;
; Setupline
+1,3,s,16,9600,DWS7410
1,77070100010800ff@1000,Energie,kWh,energy,4
1,77070100020800ff@1000,Lieferung,kWh,en_out,4
1,77070100100700ff@1,Leistung,W,power,2
1,7707010060320101@#,SID,,meter_id,0
#
