>D
;*****
; DZG-DxS7420
; 
; DZG-DVS74 4L-Drehstromzähler
; DZG-DWS74 4L-Zähler mit Option Einphasenzähler
;
;*****
; - Haken bei "Skript aktivieren" setzen
; - Skript auswaehlen
; - Speichern anklicken
;*****
>B
=>sensor53 r
;
>M 1
;
; Setupline
+1,3,s,0,9600,DWS7420
1,77070100010800ff@1000,Gesamtverbrauch,kWh,total_in,2
1,77070100020800ff@1000,Gesamteinspeisung,kWh,total_out,2
1,77070100100700ff@1,Leistung,W,power,2
1,7707010060320101@#,SID,,meter_id,0
#