>D
;*****
;
;*****
; After selecting a script, be sure to activate it and reboot!
; Nachdem auswaehlen eines Scripts, unbedingt dieses aktivieren und einen Neustart durchfuehren!
;*****
>B
=>sensor53 r
; Set teleperiod to 10sec
; Interval fuer das Senden von Daten auf 10 Sekunden setzen
tper=10
>M 1
;
; Setupline
+1,3,o,0,9600,SML
1,1-0:1.8.0*255(@1,EC_CounterVal,kWh,EC_CounterVal,4
1,1-0:61.7.255*255(@1,EC_PowerVal,W,EC_PowerVal,0
#