>D
;*****
;
;*****
; - Haken bei "Skript aktivieren" setzen
; - Skript auswaehlen
; - Speichern anklicken
;*****
>B
=>sensor53 r
;
>M 1
;
; Setupline
+1,3,s,0,9600,,1
1,77070100600100ff@#,Server-ID,,Wert,0
1,77070100010800ff@1000,Total Consumed,kWh,total_consumed_kwh,1
1,77070100020800ff@1000,Total Delivered,kWh,total_delivered_kwh,1
1,77070100100700ff@0.1,Current Consumption,W,current_consumption,0
#
