>D
;*****
; EMH-ED300L
;*****
; After selecting a script, be sure to activate it and reboot!
; Nachdem auswaehlen eines Scripts, unbedingt dieses aktivieren und einen Neustart durchfuehren!
;*****  
>B   
->sensor53 r  
>M 1  
+1,3,s,0,9600,Haus  
1,77070100100700FF@1,Leistung,W,Power_curr,1
1,77070100010800FF@1000,Verbrauch,kWh,Total_in,2
1,77070100020800FF@1000,Netzeinspeisung,kWh,Total_out,2  
#   
