>D
;*****
;
;*****
; After selecting a script, be sure to activate it and reboot!
; Nachdem auswaehlen eines Scripts, unbedingt dieses aktivieren und einen Neustart durchfuehren!
;*****
>B
=>sensor53 r
; Set teleperiod to 10sec
; Interval fuer das Senden von Daten auf 10 Sekunden setzen
tper=10
>M 1
;
; Setupline
+1,3,s,0,9600,
1,77070100010800ff@1000,Total consumption,kWh,total_in,2
1,77070100020800ff@1000,Total feed-in,kWh,total_out,2
1,77070100100700ff@1,Power,W,power_curr,0
#