>D 48
factor=100
zaehler_start=0
res=0
save=0
tmp=0
hour=0
yr=0
da=1
GasTotal=0
utm="00d 00h 00m"
M:p:dcon=0 31
M:p:mcon=0 12
M:p:g30=0 48
p:mval=0
p:dval=0
p:yval=0
m30=0
last_gas=0
avg_g=0

>B
=>sensor53 r
is(0 "Jan|Feb|Mär|Apr|Mai|Jun|Jul|Aug|Sep|Okt|Nov|Dez|")
smlj=0
=>sensor53 c1 %zaehler_start%
last_gas=sml[1]

#30min
if wm>0
then
wcs <center><div id="chart30" style="width:400px;height:250px"></div></center>
wcs <script>function draw30(){
wcs var data=google.visualization.arrayToDataTable([['Zeit','m3',{role:'style'}],
m30=int(((hours*60)+mins)/30)+1
for tmp 1 48 1
wcs [
if (tmp%4==1)
then
wcs '%int((tmp-1)/2)%h'
else
wcs ''
endif
if (tmp<m30)
then
wcs ,%g30[tmp]%,'green'],
endif
if (tmp==m30)
then
wcs ,%g30[tmp]%,'red'],
endif
if (tmp>m30)
then
wcs ,%g30[tmp]%,'blue'],
endif
next
wcs ]);
wcs var options={chartArea:{left:50,width:'80%'},legend:'none',title:'Tagesverlauf (30 min)',vAxis:{format:'#0.00'}};
wcs new google.visualization.ColumnChart(document.getElementById('chart30')).draw(data,options);}
wcs google.charts.setOnLoadCallback(draw30);</script>
endif

#daysub
if wm>0
then
wcs <center><div id="day" style="width:400px;height:250px"></div></center>
wcs <script>function drawD(){
wcs var data=google.visualization.arrayToDataTable([['Tag','m3',{role: 'style'}],
for tmp 1 dcon[-1] 1
wcs [%tmp%,%dcon[tmp]%,
if (tmp<day)
then
wcs 'green'],
endif
if (tmp==day)
then
wcs 'red'],
endif
if (tmp>day)
then
wcs 'blue'],
endif
next
wcs ]);
wcs var options={chartArea:{left:50,width:'80%'},legend:'none',title:'Monat %is[month]%',vAxis:{format:'#0.00'}};
wcs new google.visualization.ColumnChart(document.getElementById('day')).draw(data,options);}
wcs google.charts.setOnLoadCallback(drawD);</script>
endif

#monthsub
if wm>0
then
wcs <center><div id="month" style="width:400px;height:250px"></div></center>
wcs <script>function drawM(){
wcs var data=google.visualization.arrayToDataTable([['Monat','m3',{role: 'style'}],
for tmp 1 12 1
wcs ['%is[tmp]%',%mcon[tmp]%,
if (tmp<month)
then
wcs 'green'],
endif
if (tmp==month)
then
wcs 'red'],
endif
if (tmp>month)
then
wcs 'blue'],
endif
next
wcs ]);
wcs var options={chartArea:{left:50,width:'80%'},legend:'none',title:'Jahr %year%',vAxis:{format:'#0.00'}};
wcs new google.visualization.ColumnChart(document.getElementById('month')).draw(data,options);}
wcs google.charts.setOnLoadCallback(drawM);</script>
endif

>M 1
+1,14,c,1,-500,Gas
1,1-0:1.8.0*255(@%factor%,Gesamtverbrauch,m3,total,2)

>S
if (res==1)
then
res=0
dval=GasTotal
mval=GasTotal
yval=GasTotal
for tmp 1 31 1
dcon[tmp]=0
next
for tmp 1 12 1
mcon[tmp]=0
next
for tmp 1 48 1
g30[tmp]=0
next
svars
print Reset ok
endif

if (save==1)
then
save=0
svars
endif

if (year>2020)
then
if (upsecs%10==0)
then
avg_g+=sml[1]-last_gas
last_gas=sml[1]
endif

if (upsecs%60==0)
then
hour=hours
utm=s(2.0(int(uptime/1440)))+"d "+s(2.0(int(uptime/60)%24))+"h "+s(2.0(uptime%60))+"m"
GasTotal=sml[1]
dcon[day]=GasTotal-dval
mcon[month]=GasTotal-mval
m30=int(((hours*60)+mins)/30)+1
g30[m30]+=avg_g
avg_g=0

if ((chg[hour]>0) and (hour==0))
then
for tmp 1 48 1 | g30[tmp]=0 | next
if (day>1)
then
da=day
else
for tmp (da+1) 31 1 | dcon[tmp]=0 | next
mval=GasTotal
endif
if (day==1 and month==1)
then
yval=GasTotal
endif
dval=GasTotal
svars
endif
endif
endif

>W
bu(save "Sichern" "Speichern")
bu(res "Reset" "Reset")

Tagesverbrauch: {m} %2(GasTotal-dval)% m3
Monatsverbrauch: {m} %2(GasTotal-mval)% m3
Jahresverbrauch: {m} %2(GasTotal-yval)% m3

Datum: {m} %s(2.0day)%.%s(2.0month)%.%s(2.0year)% - %s(2.0hours)%:%s(2.0mins)%
Uptime: {m} %utm%

$<div style="text-align:center;">
$<script src="https://www.gstatic.com/charts/loader.js"></script>
$<script>google.charts.load('current',{packages:['corechart']});</script>

%=#30min
%=#daysub
%=#monthsub

$<center><span style="font-size:10px;">
Original by ottelo.jimdo.de - modified by waldy<br>
</span></center></div>
