>D 48
factor=100
zaehler_start=3685565
res=0
save=0
tmp=0
hour=0
yr=0
da=1
GasTotal=0
utm="00d 00h 00m"
M:p:dcon=0 31
M:p:mcon=0 12
p:mval=0
p:dval=0
p:yval=0
M:p:sday=0 288
M:p:g30=0 48
m5=0
m30=0
cstr="cnt0/12"
avgv2=0
avgvc2=0
avg_g=0
last_gas=0
tcol=""

>B
=>sensor53 r
is(0 "Jan|Feb|Mär|Apr|Mai|Jun|Jul|Aug|Sep|Okt|Nov|Dez|")
smlj=0
=>sensor53 c1 %zaehler_start%
GasTotal=sml[1]
last_gas=sml[1]

#30min
wcs <div id="chart30" style="width:400px"></div><script>function draw30(){
wcs var data=google.visualization.arrayToDataTable([['','m3',{role:'style'}],
m30=int(((hours*60)+mins)/30)+1
for tmp 1 48 1
tcol="blue"
if(tmp<m30){tcol="green"}
if(tmp==m30){tcol="red"}
wcs [
if(tmp%4==1){wcs '%int((tmp-1)/2)%h'}else{wcs ''}
wcs ,%g30[tmp]%,'%tcol%'],
next
wcs ]);new google.visualization.ColumnChart(document.getElementById('chart30')).draw(data,{chartArea:{left:40,width:'85%%'},legend:'none',title:'Verbrauch 30m',vAxis:{format:'#0.00'}});}google.charts.setOnLoadCallback(draw30);</script>

#daysub
wcs <div id="day" style="width:400px"></div><script>function drawChart(){
wcs var data=google.visualization.arrayToDataTable([['','m3',{role:'style'}],
for tmp 1 dcon[-1] 1
tcol="blue"
if(tmp<day){tcol="green"}
if(tmp==day){tcol="red"}
wcs [%tmp%,%dcon[tmp]%,'%tcol%'],
next
wcs ]);new google.visualization.ColumnChart(document.getElementById('day')).draw(data,{chartArea:{left:40,width:'85%%'},legend:'none',title:'Tage (Monat)',vAxis:{format:'#0.00'}});}google.charts.setOnLoadCallback(drawChart);</script>

#monthsub
wcs <div id="month" style="width:400px"></div><script>function drawChartM(){
wcs var data=google.visualization.arrayToDataTable([['','m3',{role:'style'}],
for tmp 1 12 1
tcol="blue"
if(tmp<month){tcol="green"}
if(tmp==month){tcol="red"}
wcs ['%is[tmp]%',%mcon[tmp]%,'%tcol%'],
next
wcs ]);new google.visualization.ColumnChart(document.getElementById('month')).draw(data,{chartArea:{left:40,width:'85%%'},legend:'none',title:'Monate',vAxis:{format:'#0.00'}});}google.charts.setOnLoadCallback(drawChartM);</script>

>M 1
+1,14,c,1,-500,Gas
1,1-0:1.8.0*255(@%factor%,Gesamtverbrauch,m3,Total_In,2)

>S
if (res==1) {
res=0
GasTotal=sml[1]
dval=GasTotal
mval=GasTotal
yval=GasTotal
last_gas=GasTotal
avgv2=0
avgvc2=0
avg_g=0
for tmp 1 31 1 | dcon[tmp]=0 | next
for tmp 1 12 1 | mcon[tmp]=0 | next
for tmp 1 48 1 | g30[tmp]=0 | next
for tmp 0 288 1 | sday[tmp]=0 | next
svars
}

if (save==1) {
save=0
svars
}

if (year>2020) {
if (upsecs%10==0) {
avg_g+=sml[1]-last_gas
last_gas=sml[1]
}
if (upsecs%60==0) {
hour=hours
yr=year
utm=s(2.0(int(uptime/1440)))+"d "+s(2.0(int(uptime/60)%24))+"h "+s(2.0(uptime%60))+"m"
GasTotal=sml[1]
dcon[day]=GasTotal-dval
mcon[month]=GasTotal-mval
m30=int(((hours*60)+mins)/30)+1
g30[m30]+=avg_g
avg_g=0
m5=int((((hours*60)+mins)/5)+1)
sday[0]=m5
if (chg[m5]>0) {
sday[m5]=avgv2
avgv2=0
}
cstr="cnth"+s(1.0(((hours)*12)+int(mins/5))+1)+"/12"
if ((chg[hour]>0) and (hour==0)) {
for tmp 2 48 1 | g30[tmp]=0 | next
if (day>1) { da=day } else {
for tmp (da+1) 31 1 | dcon[tmp]=0 | next
mval=GasTotal
}
if (day==1 and month==1) { yval=GasTotal }
dval=GasTotal
svars
}
}
}

>W
bu(save "Save" "Save")
bu(res "Reset" "Reset")

Tagesverbrauch: {m} %2(GasTotal-dval)% m3
Monatsverbrauch: {m} %2(GasTotal-mval)% m3

$<script src="https://www.gstatic.com/charts/loader.js"></script>
$<script>google.charts.load('current',{packages:['corechart']});</script>

%=#30min

$<div id="chart2" style="width:400px"></div>
$gc(lt sday "wr" "m3" cstr)
$var options={chartArea:{left:60,width:'80%%'},legend:'none',vAxis:{format:'#0.00'},series:{0:{type:'area'}},title:'24h'};
$gc(e)

%=#daysub
%=#monthsub
