>D
;*****
;
;*****
; After selecting a script, be sure to activate it and reboot!
; Nachdem auswaehlen eines Scripts, unbedingt dieses aktivieren und einen Neustart durchfuehren!
;*****
>B
=>sensor53 r
; Set teleperiod to 10sec
; Interval fuer das Senden von Daten auf 10 Sekunden setzen
tper=10
>M 1
;
; Setupline
+1,3,o,0,300,STROM,1,600,2F3F210D0A
1,1.8.1(@1,Total Consumed,kWh,Total_in,3
1,2.8.1(@1,Total Delivered,kWh,Total_out,3
1,0.0.0(@#),Meter Number,,Meter_number,0
#