>D
;*****
; TEST SCRIPT
;*****
; - Haken bei "Skript aktivieren" setzen
; - Skript auswaehlen
; - "Speichern" anklicken
;*****
>B
=>sensor53 r
;
; Set teleperiod to 10sec
; Interval fuer das Senden von Daten auf 10 Sekunden setzen
tper=10
;
>M 1
;
; Setupline
+1,3,s,0,9600,TEST
;
;1,7707010000020000@1,Unbekannter Datentyp,Unbekannte Einheit,unbekanntes_mqtt_topic_1,0
;1,7707010000020001@1,Unbekannter Datentyp,Unbekannte Einheit,unbekanntes_mqtt_topic_5,0
1,77070100010800FF@1,Zählerstand Total,Wh,zählerstand_total,1
1,=h<hr/>
;
1,77070100020800FF@1,Wirkenergie Total,Wh,wirkenergie_total,1
1,=h<hr/>
;
1,770701000E0700FF@1,Netz Frequenz,Hz,netz_frequenz,1
1,=h<hr/>
;
1,77070100100700FF@1,aktuelle Wirkleistung,W,aktuelle_wirkleistung,0
1,77070100240700FF@1,Wirkleistung L1,W,wirkleistung_l1,0
1,77070100380700FF@1,Wirkleistung L2,W,wirkleistung_l2,0
1,770701004C0700FF@1,Wirkleistung L3,W,wirkleistung_l3,0
1,=h<hr/>
;
1,770701001F0700FF@1,Strom L1,A,strom_l1,2
1,77070100330700FF@1,Strom L2,A,strom_l2,2
1,77070100470700FF@1,Strom L3,A,strom_l3,2
1,=h<hr/>
;
1,77070100200700FF@1,Spannung L1,V,spannung_l1,1
1,77070100340700FF@1,Spannung L2,V,spannung_l2,1
1,77070100480700FF@1,Spannung L3,V,spannung_l3,1
1,=h<hr/>
;
;1,77070100510701FF@1,Phasenabweichung Spannungen L1/L2,°,phasenabweichung_spannungen_l1-l2,0
;1,77070100510702FF@1,Phasenabweichung Spannungen L1/L3,°,phasenabweichung_spannungen_l1-l3,0
;1,77070100510704FF@1,Phasenabweichung Strom/Spannung L1,°,phasenabweichung_strom-spannung_l1,0
;1,7707010051070FFF@1,Phasenabweichung Strom/Spannung L2,°,phasenabweichung_strom-spannung_l2,0
;1,7707010051071AFF@1,Phasenabweichung Strom/Spannung L3,°,phasenabweichung_strom-spannung_l3,0
;1,77070100600100FF@1,Unbekannter Datentyp,Unbekannte Einheit,unbekanntes_mqtt_topic_11,0
;1,7707010060320101@1,Unbekannter Datentyp,Unbekannte Einheit,unbekanntes_mqtt_topic_9,0
;1,77070100605A0201@1,Unbekannter Datentyp,Unbekannte Einheit,unbekanntes_mqtt_topic_3,0
;1,77070100605A0202@1,Unbekannter Datentyp,Unbekannte Einheit,unbekanntes_mqtt_topic_7,0
#
