>D
;*****
; TEST SCRIPT #3
;*****
; - Haken bei "Skript aktivieren" setzen
; - Skript auswaehlen
; - "Speichern" anklicken
;*****
; protocol is OBIS ASCII
; Gerät mit hex "2F3F210D0A" = ASCII "/?!" aufwecken.
; Zaehler EMH LZQJ-XC arbeitet im "Protocol mode A" IEC 62056-21:2002(E) 6.4.1
; mit einer festen Baudrate von 300 Baud und kann nicht umgeschaltet werden
; Zaehler EMH LZQJ-XC auslesen dauert 4:21 Minuten. Kuerzere TelePeriod als 300 Sekunden daher nicht sinnvoll.
>B
=>sensor53 r
; Set teleperiod to 10sec
; Interval fuer das Senden von Daten auf 10 Sekunden setzen
tper=10
;
>M 1
;
; Setupline
;+1,3,o,0,300,METER,1,3000,2F3F210D0A
+1,3,o,0,300,METER,1,100,2F3F210D0A
;
1,0.0.0(@1,Zähler-Nr.,,0_0_0,0
1,0.0.9(@#),Zähler-ID,,0_0_9,0
1,0.9.1(@1),Uhrzeit,,0_9_1,0
1,0.9.2(@1),Datum,,0_9_1,0
1,1.6.1(@1,SpitzenlastTarif1,kW,1_6_1,3
1,1.6.2(@1,SpitzenlastTarif2,kW,1_6_2,3
1,1.8.0(@1,WirkEnBezug,kWh,1_8_0,3
1,1.8.1(@1,WirkEnBezugTarif1,kWh,1_8_1,3
1,1.8.2(@1,WirkEnBezugTarif2,kWh,1_8_2,3
1,2.6.1(@1,MaxEinspTarif1,kW,2_6_1,3
1,2.6.2(@1,MaxEinspTarif2,kW,2_6_2,3
1,2.8.0(@1,WirkEnEinsp,kWh,2_8_0,3
1,2.8.1(@1,WirkEnEinspNT,kWh,2_8_1,3
1,2.8.2(@1,WirkEnEinspHT,kWh,2_8_2,3
1,3.8.0(@1,BlindEnBezug,kvarh,3_8_0,3
1,3.8.1(@1,BlindEnBezugTarif1,kvarh,3_8_1,3
1,3.8.2(@1,BlindEnBezugTarif2,kvarh,3_8_2,3
1,4.8.0(@1,BlindEnEinsp,kvarh,4_8_0,3
1,4.8.1(@1,BlindEnEinspTarif1,kvarh,4_8_1,3
1,4.8.2(@1,lindEnEinspTarif2,kvarh,4_8_2,3
#
