>D 40
;*****
; Gaszähler TEST - DMY
;
; Tested by waldy
;*****
; - Haken bei "Skript aktivieren" setzen
; - Skript auswaehlen
; - Speichern anklicken
;*****

M:p:dcon=0 31
M:p:mcon=0 24

GasTotal=0
p:mval=0
p:dval=0
p:yval=0
tmp=0
utm="00d 00h 00m"
hour=0
yr=0
da=1
save=0


>B
=>sensor53 r
is(0 "Jan|Feb|Mär|Apr|Mai|Jun|Jul|Aug|Sep|Okt|Nov|Dez|")
smlj=0


>M 1
; Setupline
+1,14,c,1,-500,Gas
1,1-0:1.8.0*255(@100,Gesamtverbrauch,m3,total,18)
#


>S
if (save==1) {
save=0
svars
print Daten wurden gespeichert
}

if (sml[1]>0) {
smlj=1
}

if (year<2020) {
print NTP not ready
break
}

if (upsecs%60==0) {
hour=hours
yr=year
utm=s(2.0(int(uptime/1440)))+"d "+s(2.0(int(uptime/60)%24))+"h "+s(2.0(uptime%60))+"m"

GasTotal=sml[1]
dcon[day]=GasTotal-dval
mcon[month]=GasTotal-mval

if ((chg[hour]>0) and (hour==0)) {
if (day>1) {
da=day
} else {
for tmp (da+1) 31 1
dcon[tmp]=0
next
mval=GasTotal
}
if (chg[yr]>0) {
yval=GasTotal
}
dval=GasTotal
svars 
}
}

>W

bu(save "gespeichert!" "Daten sofort speichern")

Tagesverbrauch{m}%2(GasTotal-dval)% m3
Monatsverbrauch{m}%2(GasTotal-mval)% m3
Jahresverbrauch{m}%2(GasTotal-yval)% m3

Datum{m}%s(2.0day)%.%s(2.0month)%.%s(2.0year)% - %s(2.0hours)%:%s(2.0mins)%:%s(2.0secs)%
Uptime{m}%utm%
